apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.app.name }}
  labels:
    app: {{ .Values.labels.app.name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.labels.app.name }}

