replicaCount: 1
image:
  repository: 'natix02/tensor-flow-model-temp-convert'
  tag: '1.0'
  pullPolicy: IfNotPresent
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
labels:
  tfmodel:
    name: my-tf-model
service:
  port: 8501
  targetPort: 8501