replicaCount: 1
image:
  repository: 'natix02/temp-convert-flask-app'
  tag: '1.0'
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 8080
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
labels:
  app:
    name: my-app

