apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.locust.name }}
spec:
  selector:
    app: {{ .Values.labels.locust.name }}
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
