apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.labels.locust.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.locust.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8089
          command: ["locust"]
          args:
            - "-f"
            - "locustfile.py"
